// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-wNwkwuP7m72aiRsjrrQQfi9ZP3odnc',
    appId: '1:190452702662:web:aa4981e1a3af88e29726c7',
    messagingSenderId: '190452702662',
    projectId: 'chat-app-aa4b5',
    authDomain: 'chat-app-aa4b5.firebaseapp.com',
    storageBucket: 'chat-app-aa4b5.firebasestorage.app',
    measurementId: 'G-LWB76JF6KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlQyf173Qo8UThK6haGLvNnH-UZDPJ40',
    appId: '1:190452702662:android:bab0fc9a9b54e1fd9726c7',
    messagingSenderId: '190452702662',
    projectId: 'chat-app-aa4b5',
    storageBucket: 'chat-app-aa4b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvBT2Bxv2fuk_tKct6MtDJ0xn3CN2-iek',
    appId: '1:190452702662:ios:e019657a8cbb7a6a9726c7',
    messagingSenderId: '190452702662',
    projectId: 'chat-app-aa4b5',
    storageBucket: 'chat-app-aa4b5.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvBT2Bxv2fuk_tKct6MtDJ0xn3CN2-iek',
    appId: '1:190452702662:ios:e019657a8cbb7a6a9726c7',
    messagingSenderId: '190452702662',
    projectId: 'chat-app-aa4b5',
    storageBucket: 'chat-app-aa4b5.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-wNwkwuP7m72aiRsjrrQQfi9ZP3odnc',
    appId: '1:190452702662:web:ebb861ae7c2085d79726c7',
    messagingSenderId: '190452702662',
    projectId: 'chat-app-aa4b5',
    authDomain: 'chat-app-aa4b5.firebaseapp.com',
    storageBucket: 'chat-app-aa4b5.firebasestorage.app',
    measurementId: 'G-ZKRKYXM5SY',
  );
}
